export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const EMPTY_USER = "EMPTY_USER";

export const GET_USER_DETAIL_PENDING = "GET_USER_DETAIL_PENDING";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_ERROR = "GET_USER_DETAIL_ERROR";

export const GET_REPO_PENDING = "GET_REPO_PENDING";
export const GET_REPO_SUCCESS = "GET_REPO_SUCCESS";
export const GET_REPO_ERROR = "GET_REPO_ERROR";
